# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import parser_pb2 as parser__pb2


class LemillionParserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.parseData = channel.unary_unary(
        '/LemillionParser/parseData',
        request_serializer=parser__pb2.ParseRequest.SerializeToString,
        response_deserializer=parser__pb2.ParseReply.FromString,
        )


class LemillionParserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def parseData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LemillionParserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'parseData': grpc.unary_unary_rpc_method_handler(
          servicer.parseData,
          request_deserializer=parser__pb2.ParseRequest.FromString,
          response_serializer=parser__pb2.ParseReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'LemillionParser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
