# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parser.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cparser.proto\"!\n\x0cParseRequest\x12\x11\n\tpagesJSON\x18\x01 \x03(\t\" \n\nParseReply\x12\x12\n\nparagraphs\x18\x01 \x03(\t2/\n\x06Parser\x12%\n\x05parse\x12\r.ParseRequest\x1a\x0b.ParseReply\"\x00\x62\x06proto3')
)




_PARSEREQUEST = _descriptor.Descriptor(
  name='ParseRequest',
  full_name='ParseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pagesJSON', full_name='ParseRequest.pagesJSON', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=49,
)


_PARSEREPLY = _descriptor.Descriptor(
  name='ParseReply',
  full_name='ParseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paragraphs', full_name='ParseReply.paragraphs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['ParseRequest'] = _PARSEREQUEST
DESCRIPTOR.message_types_by_name['ParseReply'] = _PARSEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseRequest = _reflection.GeneratedProtocolMessageType('ParseRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARSEREQUEST,
  __module__ = 'parser_pb2'
  # @@protoc_insertion_point(class_scope:ParseRequest)
  ))
_sym_db.RegisterMessage(ParseRequest)

ParseReply = _reflection.GeneratedProtocolMessageType('ParseReply', (_message.Message,), dict(
  DESCRIPTOR = _PARSEREPLY,
  __module__ = 'parser_pb2'
  # @@protoc_insertion_point(class_scope:ParseReply)
  ))
_sym_db.RegisterMessage(ParseReply)



_PARSER = _descriptor.ServiceDescriptor(
  name='Parser',
  full_name='Parser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=85,
  serialized_end=132,
  methods=[
  _descriptor.MethodDescriptor(
    name='parse',
    full_name='Parser.parse',
    index=0,
    containing_service=None,
    input_type=_PARSEREQUEST,
    output_type=_PARSEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARSER)

DESCRIPTOR.services_by_name['Parser'] = _PARSER

# @@protoc_insertion_point(module_scope)
