# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parser.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parser.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cparser.proto\"\x1d\n\x0cParseRequest\x12\r\n\x05pages\x18\x01 \x01(\t\"\x1a\n\nParseReply\x12\x0c\n\x04text\x18\x01 \x01(\t2<\n\x0fLemillionParser\x12)\n\tparseData\x12\r.ParseRequest\x1a\x0b.ParseReply\"\x00\x62\x06proto3')
)




_PARSEREQUEST = _descriptor.Descriptor(
  name='ParseRequest',
  full_name='ParseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pages', full_name='ParseRequest.pages', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_PARSEREPLY = _descriptor.Descriptor(
  name='ParseReply',
  full_name='ParseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ParseReply.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['ParseRequest'] = _PARSEREQUEST
DESCRIPTOR.message_types_by_name['ParseReply'] = _PARSEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseRequest = _reflection.GeneratedProtocolMessageType('ParseRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARSEREQUEST,
  __module__ = 'parser_pb2'
  # @@protoc_insertion_point(class_scope:ParseRequest)
  ))
_sym_db.RegisterMessage(ParseRequest)

ParseReply = _reflection.GeneratedProtocolMessageType('ParseReply', (_message.Message,), dict(
  DESCRIPTOR = _PARSEREPLY,
  __module__ = 'parser_pb2'
  # @@protoc_insertion_point(class_scope:ParseReply)
  ))
_sym_db.RegisterMessage(ParseReply)



_LEMILLIONPARSER = _descriptor.ServiceDescriptor(
  name='LemillionParser',
  full_name='LemillionParser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=75,
  serialized_end=135,
  methods=[
  _descriptor.MethodDescriptor(
    name='parseData',
    full_name='LemillionParser.parseData',
    index=0,
    containing_service=None,
    input_type=_PARSEREQUEST,
    output_type=_PARSEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEMILLIONPARSER)

DESCRIPTOR.services_by_name['LemillionParser'] = _LEMILLIONPARSER

# @@protoc_insertion_point(module_scope)
